import {ASSETS,assetsFor,ROUNDS,roundsFor,createGame,prepareNextRound,startRound,submitTeams,revealRound,standings,riskEligible,awardWinners} from './engine.mjs';
export {ASSETS};
export function newRoom(mode='live'){
 const g=createGame(8);if(mode==='live')g.teams=[];g.phase='lobby';g.mode=mode;g.joinOpen=mode==='live';g.deadline=null;g.remaining=180;g.paused=false;g.closed=false;g.nextTeamId=mode==='live'?0:8;return g;
}
export function addTeam(g,name,tokenHash){if(g.mode!=='live'||g.phase!=='lobby'||!g.joinOpen||g.closed)throw Error('This room is not accepting new teams.');if(g.teams.length>=10)throw Error('This room already has 10 teams.');name=String(name||'').trim().replace(/\s+/g,' ');if(!name||name.length>30||/[<>\u0000-\u001f]/.test(name))throw Error('Use a team name of 1–30 characters, without angle brackets.');if(g.teams.some(t=>t.name.toLowerCase()===name.toLowerCase()))throw Error('That team name is taken. Choose another name.');const t={...createGame(6).teams[0],id:g.nextTeamId++,name,tokenHash,submittedRound:null};for(const key of ['weights','holdings','contributions'])t[key]=t[key].slice(0,assetsFor(g).length);g.teams.push(t);return t;}
export function allocate(g,id,round,weights){if(g.closed||g.phase!=='trading'||round!==g.round)throw Error('This allocation window has closed. Refresh for the current round.');const t=g.teams.find(t=>t.id===id);if(!t)throw Error('This team is no longer in the room.');if(!Array.isArray(weights)||weights.length!==assetsFor(g).length||weights.some(w=>typeof w!=='number'||!Number.isFinite(w)||w<0||w>100)||Math.abs(weights.reduce((a,b)=>a+b,0)-100)>.00001)throw Error('Allocations must total 100%, with no negative amounts.');t.weights=[...weights];t.submittedRound=g.round;g.submitted=g.teams.every(t=>t.submittedRound===g.round);}
export function hostAction(g,input,now=Date.now()){
 const a=input.action;if(g.closed)throw Error('This room has ended. Create a new room.');
 if(a==='begin'){if(g.phase!=='lobby'||!g.teams.length)throw Error('At least one team must join first.');g.phase='ready';g.joinOpen=false;}
 else if(a==='start'){startRound(g);g.teams.forEach(t=>{t.weights=t.holdings.map(v=>v/t.value*100);t.submittedRound=null});g.deadline=now+180000;g.remaining=180;g.paused=false;}
 else if(a==='prepare'){prepareNextRound(g);g.deadline=null;g.remaining=180;g.paused=false;}
 else if(a==='submit'){if(g.mode!=='practice')throw Error('Live teams submit from their iPads.');submitTeams(g);g.teams.forEach(t=>t.submittedRound=g.round);}
 else if(a==='reveal'){if(g.phase!=='trading')throw Error('There is no open allocation round.');const missing=g.teams.filter(t=>t.submittedRound!==g.round);if(missing.length&&!input.confirmCarry)throw Error('Some teams have not submitted. Confirm carrying their current holdings.');g.submitted=true;revealRound(g);g.snapshots[g.snapshots.length-1]=g.snapshots.at(-1).map(({history,tokenHash,...t})=>t);g.deadline=null;g.paused=true;}
 else if(a==='pause'){if(g.phase!=='trading')throw Error('No timer is running.');if(g.paused){g.deadline=now+g.remaining*1000;g.paused=false}else{g.remaining=Math.max(0,Math.ceil((g.deadline-now)/1000));g.deadline=null;g.paused=true;}}
 else if(a==='remove'){if(g.phase!=='lobby')throw Error('Teams can only be removed in the lobby.');g.teams=g.teams.filter(t=>t.id!==input.teamId);}
 else if(a==='close'){g.closed=true;g.joinOpen=false;g.deadline=null;}
 else throw Error('Unknown room action.');return g;
}
const safeTeam=({tokenHash,...t})=>t;
export function publicRound(r,revealed){if(revealed)return r;return {title:r.title,tag:r.tag,news:r.news,path:[],dates:[],year:null};}
export function hostView(row){const g=JSON.parse(row.state),ROUNDS=roundsFor(g),snapshots=g.snapshots.map((ts,i)=>{const length=1+ROUNDS.slice(0,i+1).reduce((a,r)=>a+r.path.length,0);return ts.map(t=>({...t,history:g.teams.find(current=>current.id===t.id).history.slice(0,length)}))});const rounds=ROUNDS.map((r,i)=>i<g.round?publicRound(r,true):i===g.round&&g.phase!=='lobby'?publicRound(r,false):null);return {code:row.code,revision:row.revision,expiresAt:row.expires_at,serverNow:Date.now(),game:{...g,teams:g.teams.map(safeTeam),snapshots},rounds};}
export function teamView(row,id){const g=JSON.parse(row.state),ROUNDS=roundsFor(g),t=g.teams.find(t=>t.id===id);if(!t)throw Error('This team was removed from the room.');const idx=Math.min(g.phase==='recap'?g.round-1:g.round,5),revealed=idx<g.round;const rank=standings(g.teams),eligible=riskEligible(g.teams);return {code:row.code,revision:row.revision,serverNow:Date.now(),phase:g.phase,closed:g.closed,round:g.round,roundIndex:idx,deadline:g.deadline,paused:g.paused,remaining:g.remaining,teamCount:g.teams.length,team:safeTeam(t),submitted:t.submittedRound===g.round&&g.phase==='trading',scenario:g.phase==='lobby'?null:publicRound(ROUNDS[idx],revealed),leaderboard:g.phase==='recap'?rank.map(p=>({id:p.id,name:p.name,value:p.value,pnl:p.pnl,drawdown:p.drawdown,eligible:eligible.some(e=>e.id===p.id)})):[],awards:g.round===6?Object.fromEntries(Object.entries(awardWinners(g.teams)).map(([k,v])=>[k,v.map(t=>t.name)])):null};}
