import {HISTORY} from './history.mjs';
const releases={
 2021:{date:'2020-12-16',url:'https://www.federalreserve.gov/newsevents/pressreleases/monetary20201216a.htm'},
 2022:{date:'2021-12-15',url:'https://www.federalreserve.gov/newsevents/pressreleases/monetary20211215a.htm'},
 2024:{date:'2023-12-13',url:'https://www.federalreserve.gov/newsevents/pressreleases/monetary20231213a.htm'},
 2025:{date:'2024-12-18',url:'https://www.federalreserve.gov/newsevents/pressreleases/monetary20241218a.htm'},
 2020:{date:'2019-12-11',url:'https://www.federalreserve.gov/newsevents/pressreleases/monetary20191211a.htm'},
 2023:{date:'2022-12-14',url:'https://www.federalreserve.gov/newsevents/pressreleases/monetary20221214a.htm'}
};
const briefs={
 2021:{title:'Support for an uneven recovery.',tag:'Low rates & recovery',news:[['MONETARY POLICY','Interest rates stay close to zero','The central bank keeps its policy rate at 0–0.25% and continues buying government and mortgage-backed securities. It wants employment and inflation to improve before withdrawing support.'],['ECONOMY','The recovery still faces a health crisis','Activity and employment have improved, but remain below their earlier levels. The public-health situation remains a major risk, while weak demand keeps inflation subdued.']],recap:'Bitcoin and the U.S. stock fund finished higher, while gold and the Treasury bond fund ended lower. A positive annual return did not eliminate substantial losses along the way.'},
 2022:{title:'Inflation builds. Support begins to slow.',tag:'Inflation & policy withdrawal',news:[['MONETARY POLICY','The central bank slows its asset purchases','Policymakers keep interest rates at 0–0.25% but reduce the pace of new government and mortgage-bond purchases. They expect further reductions as inflation stays elevated and the labor market improves.'],['ECONOMY','Recovery strengthens, but supply strains persist','Activity and employment continue to improve, with unemployment falling. Supply-demand imbalances are pushing prices higher. The public-health outlook and new virus variants remain risks to the recovery.']],recap:'Bitcoin lost about 64% over the year. The U.S. stock and Treasury bond funds also declined, while gold finished slightly lower. Holding a mix of assets did not guarantee a gain; cash provided a stable nominal value under the game rules.'},
 2024:{title:'Inflation eases. Rates stay high.',tag:'High rates & slowing growth',news:[['MONETARY POLICY','The central bank holds rates steady','Policymakers maintain a 5.25–5.50% policy-rate range and continue shrinking their securities holdings. Future decisions depend on incoming evidence and the delayed effects of earlier tightening.'],['ECONOMY','Price pressures ease as growth slows','Inflation has declined but remains elevated. Economic growth has slowed from its earlier strong pace. Hiring has moderated but remains strong, while tighter credit may weigh on households and businesses.']],recap:'Bitcoin, gold, and the U.S. stock fund finished higher, while the Treasury bond fund ended slightly lower. The path through the year still matters: final returns do not show the depth of interim losses.'},
 2025:{title:'A rate cut, with questions ahead.',tag:'Policy recalibration',news:[['MONETARY POLICY','The central bank cuts by a quarter point','Policymakers lower the policy-rate range to 4.25–4.50%. They will use incoming data and the balance of risks to decide the timing and scale of further changes.'],['ECONOMY','Growth holds up as the labor market cools','Economic activity continues to expand solidly. Labor-market conditions have eased, and unemployment is higher but still low. Inflation has moved closer to the 2% goal without reaching it.']],recap:'Gold recorded the strongest annual return among these assets. The U.S. stock and Treasury bond funds also gained, while Bitcoin ended below its starting level.'},
 2020:{title:'A steady outlook, with weak spots.',tag:'Growth & trade uncertainty',news:[['MONETARY POLICY','Policymakers pause after earlier adjustments','The central bank maintains a 1.50–1.75% policy-rate range. It considers its current stance appropriate to support continued expansion and a strong labor market.'],['ECONOMY','Households spend, while business demand lags','Employment remains strong and the economy is growing moderately. Household spending is robust, but business investment and exports remain weak. Inflation is running below the 2% objective.']],recap:'The year’s path includes a deep early sell-off followed by recovery. Bitcoin, gold, the U.S. stock fund, and the Treasury bond fund all finished higher. Full-year gains conceal the severity of the interim losses.'},
 2023:{title:'Inflation remains the central concern.',tag:'High rates & price pressure',news:[['MONETARY POLICY','Another rate increase, with more expected','The central bank raises its policy-rate range to 4.25–4.50% and expects further increases to help bring inflation back to 2%. It also continues reducing securities holdings.'],['ECONOMY','Price pressures persist despite modest growth','Spending and production are growing modestly, while hiring remains robust. Supply-demand imbalances and higher food and energy costs are sustaining inflation. An overseas war adds pressure to prices and global activity.']],recap:'The original four invested assets finished higher, led by Bitcoin and the U.S. stock fund. The year’s return and its interim drawdown measure different aspects of the investment experience.'}
};
const regionalRecap=h=>` China stocks (MCHI) returned ${h.path.at(-1)[5].toFixed(2)}%; Thai stocks (THD) returned ${h.path.at(-1)[6].toFixed(2)}%, in USD including distributions.`;
export const ROUNDS=HISTORY.map(h=>({...h,...briefs[h.year],recap:briefs[h.year].recap+regionalRecap(h),newsSource:{...releases[h.year],publisher:'Federal Reserve',title:'Federal Reserve issues FOMC statement'}}));
export const PRICE_SOURCES=[
 {name:'Bitcoin · BTC-USD',url:'https://finance.yahoo.com/quote/BTC-USD/history/',basis:'Daily USD close; calendar days, UTC.'},
 {name:'Gold · GLD',url:'https://finance.yahoo.com/quote/GLD/history/',basis:'SPDR Gold Shares ETF adjusted close; gold exposure after fund expenses.'},
 {name:'Government bonds · IEF',url:'https://finance.yahoo.com/quote/IEF/history/',basis:'iShares 7–10 Year Treasury Bond ETF adjusted close; distributions included.'},
 {name:'U.S. stocks · SPY',url:'https://finance.yahoo.com/quote/SPY/history/',basis:'SPDR S&P 500 ETF adjusted close; distributions included.'},
 {name:'China stocks · MCHI',url:'https://finance.yahoo.com/quote/MCHI/history/',basis:'iShares MSCI China ETF adjusted close in USD; distributions and currency effects included. Not a mainland-only index.'},
 {name:'Thai stocks · THD',url:'https://finance.yahoo.com/quote/THD/history/',basis:'iShares MSCI Thailand ETF adjusted close in USD; distributions and currency effects included. Not the THB SET Index.'}
];
