"""Build frozen normalized daily paths from retained Yahoo chart responses."""
import json,datetime,hashlib,math,pathlib
from zoneinfo import ZoneInfo
ROOT=pathlib.Path(__file__).resolve().parents[1]
YEARS=[2021,2022,2024,2025,2020,2023]
SYMBOLS=['BTC-USD','GLD','IEF','SPY','MCHI','THD']
sources=json.loads((ROOT/'research/price-sources.json').read_text())
series={}
for source in sources:
 symbol=source['symbol'];raw=(ROOT/'research/raw'/f'{symbol}.json').read_bytes()
 assert hashlib.sha256(raw).hexdigest()==source['sha256']
 result=json.loads(raw)['chart']['result'][0]
 tz=ZoneInfo(result['meta']['exchangeTimezoneName'])
 close=result['indicators']['adjclose'][0]['adjclose']
 assert len(close)==len(result['timestamp'])
 pairs=[(datetime.datetime.fromtimestamp(t,tz).date(),v) for t,v in zip(result['timestamp'],close) if v is not None]
 assert len(set(d for d,v in pairs))==len(pairs)
 assert all(math.isfinite(v) and v>0 for d,v in pairs)
 series[symbol]=dict(pairs)
# All six ETFs share the US trading calendar; fail if either new series has gaps.
for symbol in ['MCHI','THD']:
 assert set(series[symbol])==set(series['SPY']),f'Missing trading dates for {symbol}'
output=[];audit=[]
for year in YEARS:
 start=datetime.date(year,1,1);end=datetime.date(year,12,31)
 baseline_dates={s:max(d for d in series[s] if d<start) for s in SYMBOLS}
 bases={s:series[s][baseline_dates[s]] for s in SYMBOLS}
 latest=dict(bases);dates=[];path=[]
 for offset in range((end-start).days+1):
  date=start+datetime.timedelta(days=offset);values=[0]
  assert date in series['BTC-USD'],f'Missing BTC observation {date}'
  for symbol in SYMBOLS:
   if date in series[symbol]:latest[symbol]=series[symbol][date]
   values.append(round((latest[symbol]/bases[symbol]-1)*100,8))
  dates.append(date.isoformat());path.append(values)
 output.append({'year':year,'dates':dates,'path':path,'baselineDates':['Cash']+[baseline_dates[s].isoformat() for s in SYMBOLS]})
 audit.append({'year':year,'daily_steps':len(path),'annual_returns_pct':dict(zip(['Cash']+SYMBOLS,path[-1])),'baseline_dates':{s:d.isoformat() for s,d in baseline_dates.items()}})
(ROOT/'game/history.mjs').write_text('// Generated by scripts/build_history.py. Do not hand-edit price paths.\nexport const HISTORY='+json.dumps(output,separators=(',',':'))+';\n')
(ROOT/'research/annual-returns.json').write_text(json.dumps(audit,indent=2))
print(json.dumps(audit,indent=2))
